### ISSUE TITLE
Windows Explorer Open With Diamond.exe raised an exception

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/diamond#11]
Like the attached image.

![Capture](https://user-images.githubusercontent.com/93332305/148570347-2c57ecc1-f51c-4dea-bd0c-f6e10286ca21.PNG)

**Comment by bgeller** [comment]
What version of Windows are you running on?   Were you using a pre-compiled binary downloaded from our website? 

Please provide steps to repeat this issue and we will be happy to resolve it.

**Comment by 3oheicrw** [comment]
> What version of Windows are you running on? Were you using a pre-compiled binary downloaded from our website?
> 
> Please provide steps to repeat this issue and we will be happy to resolve it.

Windows 7 64 bit fully updated. Diamond installed using your 64 bit setup.

**Comment by bgeller** [comment]
We are not able to reproduce this error.  Please let us know the exact steps to repeat this.

**Comment by adriaandegroot** [comment]
As a wild guess, this is fixed with PR #20 (I was getting this same error dialog when running Diamond from the command-line with a single file as a parameter). To reproduce (on Linux):

- `rm ~.config/Diamond/config.json`
- `diamond example.txt` (where `example.txt` should actually exist in your current directory)

**Comment by 3oheicrw** [comment]
This is on Windows 8.1 64 bit. This is not yet fixed.

![Capture](https://user-images.githubusercontent.com/93332305/183969506-6b6342bc-a078-4b79-92d8-926ea041c3c3.PNG)

**Comment by 3oheicrw** [comment]
> As a wild guess, this is fixed with PR #20 (I was getting this same error dialog when running Diamond from the command-line with a single file as a parameter). To reproduce (on Linux):
> 
>     * `rm ~.config/Diamond/config.json`
> 
>     * `diamond example.txt` (where `example.txt` should actually exist in your current directory)

They are not yet merged your PR.
